# mdBook configuration file

[book]
title = "The Official Radare2 Book"
author = "pancake <pancake@nopcode.org>"
description = "The Official Radare2 Book"
language = "en"

[build]
create-missing = false

[output.html.search]
limit-results = 15
