name: Create documents with make

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Linting file references
        run: sys/lintrefs2.sh
      - name: Linting markdown format
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: src/.markdownlint.jsonc
          globs: src/**/*.md
      - name: Install pandoc
        run: |
          sudo apt-get --assume-yes update
          sudo apt-get --assume-yes install pandoc
      - name: Build single markdown file
        run: make one
      - name: Linting single markdown format
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: .one.markdownlint-cli2.jsonc
          globs: r2book.md
      - name: Install xelatex and md2gmi
        run: |
          sudo apt-get --assume-yes update
          sudo apt-get --assume-yes install texlive-xetex texinfo
          go install github.com/n0x1m/md2gmi@latest
      - name: Build ebooks
        run: make pdf epub info gmi one-online
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: r2book
          path: |
            r2book.md
            r2book.pdf
            r2book.epub
            r2book.info.gz
            r2book-gmi.tar.gz

  # Release creation
  check_release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    outputs:
      is_release: ${{ steps.release.outputs.is }}
      tag_name: ${{ steps.release.outputs.tag }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Download all git history and tags
      - name: Check if is a release
        run: |
          TAG="`git describe --exact-match --tags ${{ github.sha }} || true`"
          if [ -n "$TAG" ]; then
            echo "tag=$TAG" >> $GITHUB_OUTPUT
            echo "is=yes" >> $GITHUB_OUTPUT
          else
            echo "is=no" >> $GITHUB_OUTPUT
          fi
        id: release

  release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && needs.check_release.outputs.is_release == 'yes' }}
    needs:
      - check_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Download all git history and tags
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: r2book
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check_release.outputs.tag_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            r2book.pdf
            r2book.md
            r2book.epub
            r2book.info.gz
            r2book-gmi.tar.gz
